---
title: "BSTA662 Final Project Preliminary Analysis"
author: "Esther Ki"
format: html
---

```{r}
library(pacman)
p_load(tidyverse, knitr, kableExtra)
library(KMsurv)
data("pneumon")
```

```{r}
pneumon$region <- factor(pneumon$region)
pneumon$race <- factor(pneumon$race)
pneumon$hospital <- factor(pneumon$hospital)

levels(pneumon$region) <- c("northeast", "north central", "south", "west")
levels(pneumon$race) <- c("white", "black", "other")
```


```{r}
# write.csv(pneumon, "/Users/estherkey/Desktop/pneumon.csv", row.names = FALSE)
```

```{r}
tb <- table(pneumon$hospital)
prop.table(tb) * 100
tb
```


```{r}
summary_tb <- pneumon |> 
  group_by(hospital) |> 
  summarise(
    count = n(),
    chldage_mean = mean(chldage),
    chldage_sd = sd(chldage),
    mthage_mean = mean(mthage),
    mthage_sd = sd(mthage),
    urban_mean = mean(urban),
    urban_sd = sd(urban),
    alcohol_mean = mean(alcohol),
    alcohol_sd = sd(alcohol),
    smoke_mean = mean(smoke),
    smoke_sd = sd(smoke),
    poverty_mean = mean(poverty),
    poverty_sd = sd(poverty),
    bweight_mean = mean(bweight),
    bweight_sd = sd(bweight),
    nsibs_mean = mean(nsibs),
    nsibs_sd = sd(nsibs),
    wmonth_mean = mean(wmonth),
    wmonth_sd = sd(wmonth),
    sfmonth_mean = mean(sfmonth),
    sfmonth_sd = sd(sfmonth),
    agepn_mean = mean(agepn),
    agepn_sd = sd(agepn)
  )


kable(summary_tb, "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

```{r}
summary_tb <- pneumon |> 
  group_by(hospital) |> 
  summarise(
    count = n(),
    chldage_mean = mean(chldage),
    mthage_mean = mean(mthage),
    urban_mean = mean(urban),
    alcohol_mean = mean(alcohol),
    smoke_mean = mean(smoke),
    poverty_mean = mean(poverty),
    bweight_mean = mean(bweight),
    nsibs_mean = mean(nsibs),
    wmonth_mean = mean(wmonth),
    sfmonth_mean = mean(sfmonth),
    agepn_mean = mean(agepn),
  )


kable(summary_tb, "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

```{r}
summary_tb1 <- pneumon |> 
  group_by(hospital) |> 
  summarise(
    count = n(),
    chldage_sd = sd(chldage),
    mthage_sd = sd(mthage),
    urban_sd = sd(urban),
    alcohol_sd = sd(alcohol),
    smoke_sd = sd(smoke),
    poverty_sd = sd(poverty),
    bweight_sd = sd(bweight),
    nsibs_sd = sd(nsibs),
    wmonth_sd = sd(wmonth),
    sfmonth_sd = sd(sfmonth),
    agepn_sd = sd(agepn),
  )


kable(summary_tb1, "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```


```{r}
censored <- pneumon |>
  filter(hospital == "0")

censored <- censored %>%
  mutate_at(vars(urban, alcohol, smoke, poverty, bweight), factor)
```

```{r}
uncsrd <- pneumon |> 
  filter(hospital == "1")

uncsrd <- uncsrd %>%
  mutate_at(vars(urban, alcohol, smoke, poverty, bweight), factor)
```

```{r}
ggplot(censored) +
  geom_bar(aes(x=region), fill = "coral1") +
  labs(title = "Distribution of region in censored group") +
  theme_bw()

ggplot(uncsrd) +
  geom_bar(aes(x=region), fill = "aquamarine3")+
  labs(title = "Distribution of region in uncensored group") +
  theme_bw()
```

```{r}
ggplot(censored) +
  geom_bar(aes(x=race), fill = "coral1") +
  labs(title = "Distribution of race in censored group") +
  theme_bw()

ggplot(uncsrd) +
  geom_bar(aes(x=race), fill = "aquamarine3")+
  labs(title = "Distribution of race in uncensored group") +
  theme_bw()
```

```{r}

levels(censored$bweight) <- c("<5.5lbs", ">5.5lbs (normal)")
levels(uncsrd$bweight) <- c("<5.5lbs", ">5.5lbs (normal)")

ggplot(censored) +
  geom_bar(aes(x=bweight), fill = "coral1") +
  labs(title = "Distribution of birth weight in censored group") +
  theme_bw()

ggplot(uncsrd) +
  geom_bar(aes(x=bweight), fill = "aquamarine3")+
  labs(title = "Distribution of birth weight in uncensored group") +
  theme_bw()
```

```{r}
censored <- censored |> 
  mutate(smoke2 = case_when(smoke == "1" ~ "Yes",
                              smoke == "2" ~ "Yes",
                              TRUE ~ "No"))

uncsrd <- uncsrd |> 
    mutate(smoke2 = case_when(smoke == "1" ~ "Yes",
                              smoke == "2" ~ "Yes",
                              TRUE ~ "No"))

ggplot(censored) +
  geom_bar(aes(x=smoke2), fill = "coral1") +
  labs(title = "Distribution of smoke in censored group",
       x = "smoke") +
  theme_bw()

ggplot(uncsrd) +
  geom_bar(aes(x=smoke2), fill = "aquamarine3")+
  labs(title = "Distribution of smoke in uncensored group",
       x = "smoke") +
  theme_bw()

```

```{r}
sumstat2 <- data.frame(whichstat = c("mean"),
                      value = mean(censored$nsibs))
sumstat3 <- data.frame(whichstat = c("mean"),
                      value = mean(uncsrd$nsibs))

ggplot(censored) +
  geom_histogram(aes(x=nsibs),binwidth=0.8, fill = "coral1") +
  geom_vline(data=sumstat2,aes(xintercept = value,
                               linetype = whichstat,
                               fill = "blue"), size=1) +
  labs(title = "Distribution of number of siblings in censored group",
       x = "Number of Siblings") +
  theme_bw()

ggplot(uncsrd) +
  geom_histogram(aes(x=nsibs),binwidth=0.8, fill = "aquamarine3") + 
  labs(title = "Distribution of number of siblings in uncensored group",
       x = "Number of Siblings") +
  geom_vline(data=sumstat3,aes(xintercept = value,
                               linetype = whichstat,
                               col = whichstat), size=1) +
  theme_bw()
```

```{r}
sumstat <- data.frame(whichstat = c("mean"),
                      value = mean(uncsrd$wmonth))
ggplot(uncsrd) +
  geom_histogram(aes(x=wmonth),binwidth=2, fill = "aquamarine3") + 
  geom_vline(data=sumstat,aes(xintercept = value,
                               linetype = whichstat,
                               col = whichstat), size=1) +
  labs(title = "Distribution of month the child was weaned in uncensored group",
       x = "Month the child was weaned") +
  theme_bw()
```

```{r}
sumstat1 <- data.frame(whichstat = c("mean"),
                      value = mean(censored$wmonth))

ggplot(censored) +
  geom_histogram(aes(x=wmonth),binwidth=2, fill = "coral1") +
  geom_vline(data=sumstat1,aes(xintercept = value,
                               linetype = whichstat,
                               fill = "blue"), size=1) +
  labs(title = "Distribution of month the child was weaned in censored group",
       x = "Month the child was weaned") +
  theme_bw()

```

```{r}
sumstat4 <- data.frame(whichstat = c("mean"),
                      value = mean(censored$sfmonth))

ggplot(censored) +
  geom_histogram(aes(x=sfmonth),binwidth=2, fill = "coral1") +
  geom_vline(data=sumstat1,aes(xintercept = value,
                               linetype = whichstat,
                               fill = "blue"), size=1) +
  labs(title = "Distribution of month the child on solid food in censored group",
       x = "Month the child on solid food") +
  theme_bw()
```

```{r}
sumstat5 <- data.frame(whichstat = c("mean"),
                      value = mean(uncsrd$sfmonth))

ggplot(uncsrd) +
  geom_histogram(aes(x=sfmonth),binwidth=2, fill = "aquamarine3") +
  geom_vline(data=sumstat1,aes(xintercept = value,
                               linetype = whichstat), size=1) +
  labs(title = "Distribution of month the child on solid food in uncensored group",
       x = "Month the child on solid food") +
  theme_bw()
```

```{r}
pneumon$nsibs_fct <- as.factor(pneumon$nsibs)

ggplot(aes(nsibs_fct), data = pneumon) +
  geom_bar(fill = "darkorange") +
  theme_bw() +
  labs(title = "Distribution of number of siblings (nsibs)", 
       x = "number of siblings")
```


```{r}
pneumon1 <- pneumon |> 
  mutate(nsibs1 = case_when(nsibs == "1"~"1",
                           nsibs == "0" ~ "0",
                              TRUE ~ "2+"))
```

```{r}
ggplot(aes(nsibs1), data = pneumon1) +
  geom_bar(fill = "darkorange") +
  theme_bw() +
  labs(title = "Distribution of categorized nsibs",
       x = "number of siblings")
```


```{r}
# Calculate percentage of observations with the same values
percentage_same <- mean(pneumon$chldage == pneumon$agepn) * 100

# Print the percentage
cat("Percentage of observations with the same values:", percentage_same, "%\n")
```



